# -*- coding: utf-8 -*-
"""telephonedirectory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ho5ZxVvMgISJtHXtpomcPfITX0tabVF4
"""

import pymongo

# Telephone directory and curd operation

#creating a database

data = pymongo.MongoClient("mongodb://apurva:apurva@cluster0-shard-00-00.yewla.mongodb.net:27017,cluster0-shard-00-01.yewla.mongodb.net:27017,cluster0-shard-00-02.yewla.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-118hpd-shard-0&authSource=admin&retryWrites=true&w=majority")

db = data["TELEPHONE_DIRECTORY"]

# Creating Collections

a = db["Directory"]

# Inserting Records into the collections

a.insert_many([{"Name":"Apurva","Phone_number":1234345568,"location":"Nagpur","Age":24},{"Name":"Anjali","Phone_number":1224686788,"location":"Hydrabad","Age":25},{"Name":"Ajay","Phone_number":1234567890,"location":"Manali","Age":24},{"Name":"Apurva","Phone_number":1234545678,"location":"Nagpur","Age":21},{"Name":"Haldiram","Phone_number":121116789,"location":"Nagpur","Age":39},{"Name":"Sangita","Phone_number":1232212345,"location":"Nashik","Age":30},{"Name":"Anil","Phone_number":123333789,"location":"Mumbai","Age":33},{"Name":"Deepkia","Phone_number":128886789,"location":"Delhi","Age":44}])

# Modifying Records

a.update_one({"Name":"Anjali"},{"$set":{"place":"Chennai"}})

for item in a.find():
  print(item)

a.delete_one({"name":"Haldiram"})

for item in a.find():
  print(item)